sudo: required
dist: bionic
language: node_js
node_js:
    - '14'

notifications:
    slack:
        if: branch = master
        rooms:
            - energywebfoundation:lS0R4jfZryd9btZaw5A7MZTX#origin-updates

services: postgresql

env:
    global:
        - DB_PASSWORD=
        - DB_DATABASE=origin

git:
    depth: false

before_install:
    - sh scripts/restore-original-timestamps.sh
    - git fetch origin master:master
    - psql -c 'create database origin;' -U postgres

before_deploy:
    - git config --global user.email ${GITHUB_EMAIL}
    - git config --global user.name ${GITHUB_USER}
    - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/energywebfoundation/origin.git" > /dev/null 2>&1
    - git reset --hard
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
    - npm whoami
    - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

install:
    - set -e
    - yarn

script:
    - set -e
    - yarn build
    - if [ $TRAVIS_PULL_REQUEST != "false" ] || [ $TRAVIS_BRANCH != "master"]; then yarn lint; fi
    - if [ $TRAVIS_PULL_REQUEST != "false" ] || [ $TRAVIS_BRANCH != "master"]; then yarn test:ci:contracts; fi
    - if [ $TRAVIS_PULL_REQUEST != "false" ] || [ $TRAVIS_BRANCH != "master"]; then yarn test:ci:apps; fi
    - if [ $TRAVIS_PULL_REQUEST != "false" ] || [ $TRAVIS_BRANCH != "master"]; then yarn test:ci:e2e; fi

deploy:
    - provider: script
      script: 'git checkout master && yarn publish:canary && npx sleep 5 && yarn build:containers:canary && yarn deploy:heroku:canary'
      skip_cleanup: true
      on:
          node: '14'
          branch: master
    - provider: script
      edge: true
      script: 'git checkout release && yarn publish:release && npx sleep 5 && yarn build:containers:release'
      on:
          node: '14'
          branch: release
          condition: '$TRAVIS_COMMIT_MESSAGE != *"skip-deploy"*'
    - provider: script
      script: 'git checkout preview && yarn publish:preview'
      skip_cleanup: true
      on:
          node: '14'
          branch: preview
